version: '3.11'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"  # Redis default port

  fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      OLLAMA_API_URL: http://host.docker.internal:11434/api/chat

  celery:
    build: .
    command: celery -A tasks worker --loglevel=info
    environment:
      OLLAMA_API_URL: http://host.docker.internal:11434/api/chat
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CELERY_WORKER_CONCURRENCY: 1
      CELERY_WORKER_PREFETCH: 1
    volumes:
      - .:/app
    depends_on:
      - redis
